import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
    <div>
      <Head>
        <title>ThreadsUnveiled</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello World</h1>
      <div className="bg-slate-500">this is me</div>
    </div>
    </>
  )
}
